### ISSUE TITLE
Documentation states word_index as program argument

### ISSUE THREAD

**Issue by fnielsen** [riedlma/SECOS#2]
Documentation states word_index as program argument

`min_word_count(50) word_index prefix_length(3)` : Here `word_index` is never used.

**Comment by riedlma** [comment]
Hi,

thanks for the message!

as far as I see in the source code, the word_index is used to check in which column the word is contained that needs to be segmented (see line 29 and 262 for the file decompound_secos.py).

edit:
just realized, this was not for the decompound_secos script but for the server! I changed the source code and will also change the documentation!

Thanks a lot for that comment!!!

Best,
Martin
